#!/usr/bin/env python3
"""Sync Claude Code MCP config into project-local Codex config.

This bridge intentionally keeps environment-specific MCP definitions out of the
shared `settings.json` baseline. Instead, it reads the local/project CC config
layers that may already be active for this repo and materializes a
project-scoped `.codex/config.toml` so Codex can see the same MCP servers.

Supported sources:
1. Enabled plugin MCP definitions (installed plugin cache first, marketplace fallback)
2. `mcpServers` declared in CC settings layers
3. Project `.mcp.json` (respecting `enableAllProjectMcpServers` /
   `enabledMcpjsonServers` when present)
4. Explicitly allowed `mcp__<server>` tool permissions backed by
   `claude mcp get <server>`
"""

from __future__ import annotations

import json
import shlex
import subprocess
import sys
from collections import OrderedDict
from pathlib import Path
from typing import Any


CLAUDE_DIR = Path.home() / ".claude"
PROJECT_ROOT = CLAUDE_DIR
OUTPUT_PATH = PROJECT_ROOT / ".codex" / "config.toml"
HEADER = (
    "# Auto-generated by ~/.claude/hooks/codex-sync/sync-mcp-to-codex.py\n"
    "# Do not edit by hand; update Claude Code MCP config sources instead.\n"
)


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return {}


def load_settings_layers() -> list[tuple[Path, dict[str, Any]]]:
    layers = [
        PROJECT_ROOT / "settings.json",
        PROJECT_ROOT / "settings.local.json",
        PROJECT_ROOT / ".claude" / "settings.json",
        PROJECT_ROOT / ".claude" / "settings.local.json",
    ]
    return [(path, load_json(path)) for path in layers if path.exists()]


def load_project_mcp() -> tuple[Path, dict[str, Any]]:
    path = PROJECT_ROOT / ".mcp.json"
    return path, load_json(path)


def normalize_mcp_root(data: dict[str, Any]) -> OrderedDict[str, dict[str, Any]]:
    root = data.get("mcpServers", data)
    if not isinstance(root, dict):
        return OrderedDict()
    servers: OrderedDict[str, dict[str, Any]] = OrderedDict()
    for name, config in root.items():
        if isinstance(config, dict):
            servers[name] = config
    return servers


def enabled_plugin_refs(
    settings_layers: list[tuple[Path, dict[str, Any]]],
) -> list[str]:
    refs: OrderedDict[str, None] = OrderedDict()
    for _, data in settings_layers:
        enabled_plugins = data.get("enabledPlugins")
        if not isinstance(enabled_plugins, dict):
            continue
        for plugin_ref, enabled in enabled_plugins.items():
            if enabled and isinstance(plugin_ref, str) and "@" in plugin_ref:
                refs[plugin_ref] = None
    return list(refs.keys())


def plugin_install_paths(plugin_refs: list[str]) -> dict[str, Path]:
    installed = load_json(PROJECT_ROOT / "plugins" / "installed_plugins.json")
    plugins = installed.get("plugins")
    if not isinstance(plugins, dict):
        return {}

    result: dict[str, Path] = {}
    for plugin_ref in plugin_refs:
        entries = plugins.get(plugin_ref)
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            install_path = entry.get("installPath")
            if isinstance(install_path, str):
                result[plugin_ref] = Path(install_path)
                break
    return result


def plugin_mcp_candidate_paths(plugin_ref: str) -> list[Path]:
    plugin_name, marketplace = plugin_ref.split("@", 1)
    marketplace_root = PROJECT_ROOT / "plugins" / "marketplaces" / marketplace
    return [
        marketplace_root / ".mcp.json",
        marketplace_root / plugin_name / ".mcp.json",
        marketplace_root / "plugin" / ".mcp.json",
        marketplace_root / "plugins" / plugin_name / ".mcp.json",
        marketplace_root / "external_plugins" / plugin_name / ".mcp.json",
    ]


def replace_plugin_root(value: Any, plugin_root: Path) -> Any:
    if isinstance(value, str):
        return value.replace("${CLAUDE_PLUGIN_ROOT}", str(plugin_root))
    if isinstance(value, list):
        return [replace_plugin_root(item, plugin_root) for item in value]
    if isinstance(value, dict):
        return {
            key: replace_plugin_root(item, plugin_root)
            for key, item in value.items()
        }
    return value


def load_enabled_plugin_mcp_servers(
    plugin_refs: list[str],
) -> OrderedDict[str, dict[str, Any]]:
    servers: OrderedDict[str, dict[str, Any]] = OrderedDict()
    install_paths = plugin_install_paths(plugin_refs)

    for plugin_ref in plugin_refs:
        plugin_root = install_paths.get(plugin_ref)
        candidate_paths: list[Path] = []
        if plugin_root:
            candidate_paths.append(plugin_root / ".mcp.json")
        candidate_paths.extend(plugin_mcp_candidate_paths(plugin_ref))

        for mcp_path in candidate_paths:
            data = load_json(mcp_path)
            if not data:
                continue
            resolved_root = plugin_root if plugin_root and mcp_path.parent == plugin_root else mcp_path.parent
            for name, config in normalize_mcp_root(data).items():
                servers[name] = replace_plugin_root(config, resolved_root)
            break

    return servers


def load_settings_mcp_servers(
    settings_layers: list[tuple[Path, dict[str, Any]]],
) -> OrderedDict[str, dict[str, Any]]:
    servers: OrderedDict[str, dict[str, Any]] = OrderedDict()
    for _, data in settings_layers:
        for name, config in normalize_mcp_root({"mcpServers": data.get("mcpServers", {})}).items():
            servers[name] = config
    return servers


def project_mcp_policy(
    settings_layers: list[tuple[Path, dict[str, Any]]],
) -> tuple[bool, set[str]]:
    enable_all = False
    enabled_subset: set[str] = set()
    for _, data in settings_layers:
        if "enableAllProjectMcpServers" in data:
            enable_all = bool(data.get("enableAllProjectMcpServers"))
        value = data.get("enabledMcpjsonServers")
        if isinstance(value, list):
            enabled_subset = {item for item in value if isinstance(item, str)}
    return enable_all, enabled_subset


def filter_project_mcp_servers(
    project_mcp: dict[str, Any],
    enable_all: bool,
    enabled_subset: set[str],
) -> OrderedDict[str, dict[str, Any]]:
    servers: OrderedDict[str, dict[str, Any]] = OrderedDict()
    for name, config in normalize_mcp_root(project_mcp).items():
        if enable_all or not enabled_subset or name in enabled_subset:
            servers[name] = config
    return servers


def permission_hint_mcp_names(
    settings_layers: list[tuple[Path, dict[str, Any]]],
) -> list[str]:
    names: OrderedDict[str, None] = OrderedDict()
    for _, data in settings_layers:
        permissions = data.get("permissions")
        if not isinstance(permissions, dict):
            continue
        allow = permissions.get("allow")
        if not isinstance(allow, list):
            continue
        for item in allow:
            if not isinstance(item, str) or not item.startswith("mcp__"):
                continue
            server_name = item[len("mcp__") :].split("__", 1)[0].strip()
            if server_name:
                names[server_name] = None
    return list(names.keys())


def parse_claude_mcp_get_output(output: str) -> dict[str, Any] | None:
    config: dict[str, Any] = {}
    in_env = False

    for raw_line in output.splitlines():
        line = raw_line.rstrip()
        if not line.startswith("  "):
            continue

        stripped = line.strip()
        if in_env and ":" in stripped:
            key, value = stripped.split(":", 1)
            config.setdefault("env", {})[key.strip()] = value.strip()
            continue

        if ":" not in stripped:
            continue

        key, value = stripped.split(":", 1)
        key = key.strip().lower()
        value = value.strip()
        in_env = key == "environment"

        if key == "type":
            config["type"] = value
        elif key == "command" and value:
            config["command"] = value
        elif key == "args":
            config["args"] = shlex.split(value) if value else []
        elif key == "url" and value:
            config["url"] = value

    return config or None


def load_permission_hint_mcp_servers(
    names: list[str],
) -> OrderedDict[str, dict[str, Any]]:
    servers: OrderedDict[str, dict[str, Any]] = OrderedDict()
    for name in names:
        try:
            result = subprocess.run(
                ["claude", "mcp", "get", name],
                capture_output=True,
                text=True,
                timeout=8,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired):
            continue

        if result.returncode != 0:
            continue

        parsed = parse_claude_mcp_get_output(result.stdout)
        if parsed:
            servers[name] = parsed
    return servers


def toml_key(key: str) -> str:
    if key.replace("_", "").replace("-", "").isalnum():
        return key
    return json.dumps(key, ensure_ascii=False)


def toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    raise TypeError(f"Unsupported TOML value: {value!r}")


def emit_server(name: str, config: dict[str, Any]) -> list[str]:
    lines = [f"[mcp_servers.{toml_key(name)}]"]
    nested: list[tuple[str, dict[str, Any]]] = []

    for key, value in config.items():
        if isinstance(value, dict):
            nested.append((key, value))
            continue
        lines.append(f"{toml_key(key)} = {toml_value(value)}")

    for key, nested_dict in nested:
        lines.append("")
        lines.append(f"[mcp_servers.{toml_key(name)}.{toml_key(key)}]")
        for nested_key, nested_value in nested_dict.items():
            if isinstance(nested_value, dict):
                continue
            lines.append(f"{toml_key(nested_key)} = {toml_value(nested_value)}")

    return lines


def render_config(servers: OrderedDict[str, dict[str, Any]]) -> str:
    body: list[str] = [HEADER.rstrip(), ""]
    for index, (name, config) in enumerate(servers.items()):
        if index:
            body.append("")
        body.extend(emit_server(name, config))
    body.append("")
    return "\n".join(body)


def main() -> int:
    settings_layers = load_settings_layers()
    project_mcp_path, project_mcp_data = load_project_mcp()
    plugin_refs = enabled_plugin_refs(settings_layers)

    merged_servers: OrderedDict[str, dict[str, Any]] = OrderedDict()

    for name, config in load_enabled_plugin_mcp_servers(plugin_refs).items():
        merged_servers[name] = config

    for name, config in load_settings_mcp_servers(settings_layers).items():
        merged_servers[name] = config

    enable_all, enabled_subset = project_mcp_policy(settings_layers)
    for name, config in filter_project_mcp_servers(
        project_mcp_data, enable_all, enabled_subset
    ).items():
        merged_servers[name] = config

    permission_hint_names = permission_hint_mcp_names(settings_layers)
    for name, config in load_permission_hint_mcp_servers(permission_hint_names).items():
        merged_servers.setdefault(name, config)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    if not merged_servers:
        if OUTPUT_PATH.exists() and OUTPUT_PATH.read_text(encoding="utf-8").startswith(HEADER):
            OUTPUT_PATH.unlink()
            print(f"Removed empty generated Codex MCP config: {OUTPUT_PATH}")
        else:
            print("No shareable MCP servers found for Codex bridge.")
        return 0

    content = render_config(merged_servers)

    if OUTPUT_PATH.exists():
        existing = OUTPUT_PATH.read_text(encoding="utf-8")
        if not existing.startswith(HEADER):
            print(
                f"Refusing to overwrite unmanaged file: {OUTPUT_PATH}",
                file=sys.stderr,
            )
            return 1
        if existing == content:
            print(f"Codex MCP config already up to date: {OUTPUT_PATH}")
            return 0

    OUTPUT_PATH.write_text(content, encoding="utf-8")

    sources = [str(path) for path, _ in settings_layers]
    if project_mcp_path.exists():
        sources.append(str(project_mcp_path))
    if permission_hint_names:
        sources.append("claude mcp get:" + ",".join(permission_hint_names))
    print(
        f"Synced {len(merged_servers)} MCP server(s) into {OUTPUT_PATH}\n"
        f"Sources: {', '.join(sources)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
